version: '3.8'
#include:
#  - ../pgrsyslog-client/docker-compose.yaml
services:
  msfrpcd:
    env_file:        .env
    image:           innovanon/msfrpcd
    container_name:  bash
    ports:
      - "0.0.0.0:55553:55553"
    command: ["-U", $MSFRPC_USERNAME, "-P", $MSFRPC_PASSWORD]
    volumes:
      - msfrpcd:/usr/share/metasploit-framework/config:rw
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    depends_on:
      postgres:
        condition:   service_healthy
      syslog:
        condition:   service_started

volumes:
  msfrpcd:

